### PR TITLE
Add DASG PR template

### PR DESCRIPTION
**Pull request by dtisza1**
**JIRA Ticket:**
[SOMEPROJECT-42](https://jira.cms.gov/browse/SOMEPROJECT-42)

**User Story or Bug Summary:**

This adds a PR template. This summary is using the template.

### What Should Reviewers Watch For?

If you're reviewing this PR, please check these things, in particular:

- TODO

### CODE REVIEW

**Review by JFU-GIT — APPROVED** [review]
Looks good

**Comment by nbragdon** [comment]
@dtisza1 Should we update this template at all? Quite a bit of it isn't really relevant for a non-server project

**Comment by dtisza1** [comment]
> @dtisza1 Should we update this template at all? Quite a bit of it isn't really relevant for a non-server project

@nbragdon You're right. What do you think of a stripped down version?  Or maybe leave this out of the SDK repos?

**Review by oragame — APPROVED** [review]
LGTM!

**Pull request merged**
