### PR TITLE
[BB2-1657] Node SDK consume error config load failed

### PR DESCRIPTION
**Pull request by JFU-GIT**
**JIRA Ticket:**
[BB2-1657](https://jira.cms.gov/browse/BB2-1657)

**User Story or Bug Summary:**
Description:

When final testing the SDK, the app that consumes the SDK run into error when starting:

yarn run v1.22.19
$ node --inspect=0.0.0.0:9229 ./node_modules/.bin/ts-node ./index.ts
Debugger listening on ws://0.0.0.0:9229/49f883f1-2d13-4011-82ba-84fdab72e886
For help, see: https://nodejs.org/en/docs/inspector
/mnt/c/FORK_CMS_BB2_BFD_DEVLOCAL/BB2-NODE-SDK-TESTER-2/node_modules/cms-bluebutton-sdk/dist/cms-bluebutton-sdk.cjs.js:328
throw new Error(`Failed to load config file at: ${config}`);
^
Error: Failed to load config file at: /mnt/c/FORK_CMS_BB2_BFD_DEVLOCAL/BB2-NODE-SDK-TESTER-2/.bluebutton-config.json
at new BlueButton (/mnt/c/FORK_CMS_BB2_BFD_DEVLOCAL/BB2-NODE-SDK-TESTER-2/node_modules/cms-bluebutton-sdk/dist/cms-bluebutton-sdk.cjs.js:328:23)
at Object.<anonymous> (/mnt/c/FORK_CMS_BB2_BFD_DEVLOCAL/BB2-NODE-SDK-TESTER-2/index.ts:7:12)
at Module._compile (node:internal/modules/cjs/loader:1119:14)
at Module.m._compile (/mnt/c/FORK_CMS_BB2_BFD_DEVLOCAL/BB2-NODE-SDK-TESTER-2/node_modules/ts-node/src/index.ts:1618:23)
at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
at Object.require.extensions.<computed> [as .ts] (/mnt/c/FORK_CMS_BB2_BFD_DEVLOCAL/BB2-NODE-SDK-TESTER-2/node_modules/ts-node/src/index.ts:1621:12)
at Module.load (node:internal/modules/cjs/loader:997:32)
at Function.Module._load (node:internal/modules/cjs/loader:838:12)
at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
at phase4 (/mnt/c/FORK_CMS_BB2_BFD_DEVLOCAL/BB2-NODE-SDK-TESTER-2/node_modules/ts-node/src/bin.ts:649:14)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

It seems that the path to config file (in this case the default location is used) is not correct, the configuration file load logic can not find the file.

This needs to be fixed before SDK publish.

Acceptance Criteria:

The bug fixed so that the configuration at default location can be located correctly.

### What Does This PR Do?

1. Improve the error reporting and error message details added so that exact root cause is revealed during SDK config loading
2. Fix unit tests and added new test cases to cover the improved error reporting.

### What Should Reviewers Watch For?

If you're reviewing this PR, please check these things, in particular:

- TODO

### What Security Implications Does This PR Have?

Submitters should complete the following questionnaire:

- If the answer to any of the questions below is **Yes**, then here's a link to the associated Security Impact Assessment (SIA), security checklist, or other similar document in Confluence: N/A.
  - Does this PR add any new software dependencies? **No**.
  - Does this PR modify or invalidate any of our security controls? **No**.
  - Does this PR store or transmit data that was not stored or transmitted before? **No**.
- If the answer to any of the questions below is **Yes**, then please add StewGoin as a reviewer, and note that this PR should not be merged unless/until he also approves it.
  - Do you think this PR requires additional review of its security implications for other reasons? **No**.

### What Needs to Be Merged and Deployed Before this PR?

This PR cannot be either merged or deployed until the following pre-requisite changes have been fully deployed:

- CMSgov/some_repo#42

I have gone through and verified that...:

- [x] This PR is reasonably limited in scope, to help ensure that:
  1. It doesn't unnecessarily tie a bunch of disparate features, fixes, refactorings, etc. together.
  4. There isn't too much of a burden on reviewers.
  5. Any problems it causes have a small "blast radius".
  6. It'll be easier to rollback if that becomes necessary.
- [x] I have named this PR and its branch such that they'll be automatically be linked to the (most) relevant Jira issue, per: <https://confluence.atlassian.com/adminjiracloud/integrating-with-development-tools-776636216.html>.
- [x] This PR includes any required documentation changes, including `README` updates and changelog / release notes entries.
- [x] All new and modified code is appropriately commented, such that the what and why of its design would be reasonably clear to engineers, preferably ones unfamiliar with the project.
- [x] All tech debt and/or shortcomings introduced by this PR are detailed in `TODO` and/or `FIXME` comments, which include a JIRA ticket ID for any items that require urgent attention.
- [x] Reviews are requested from both:
  - At least two other engineers on this project, at least one of whom is a senior engineer or owns the relevant component(s) here.
  - Any relevant engineers on other projects (e.g. BFD, SLS, etc.).
- [x] Any deviations from the other policies in the [DASG Engineering Standards](https://github.com/CMSgov/cms-oeda-dasg/blob/master/policies/engineering_standards.md) are specifically called out in this PR, above.
  - Please review the standards every few months to ensure you're familiar with them.

### CODE REVIEW

**Review by dtisza1 — APPROVED** [review]
@JFU-GIT This looks good to me!

I was able to test using your instruction from the Jira story.

Steps 1-10 work well. I'm assuming step 11 is good, but didn't get it working. I'll also test later with the sample app w/ SDK PR.

Good work on this.  Also, TY for updating the license.

**Comment by ajshred** [comment]
> @JFU-GIT This looks good to me!
> 
> I was able to test using your instruction from the Jira story.
> 
> Steps 1-10 work well. I'm assuming step 11 is good, but didn't get it working. I'll also test later with the sample app w/ SDK PR.
> 
> Good work on this. Also, TY for updating the license.

Step 11 didn't work for me either James.  Is there another step to this that is missing?

A file that needs created or something?

**Review by ajshred — APPROVED** [review]
It works for me now.  Thanks James!!!

**Review by dtisza1 — APPROVED** [review]
@JFU-GIT This looks good to me!

Previously I didn't test step 11 from your instruction in Jira.

I was able to successfully test this.  I first tried out the main SDK branch to see the previous error messaging.  Then tested with this branch to see the improved messaging.

Good work on this!

**Pull request merged**
